# Generated by Django 4.0.4 on 2022-05-31 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_restaurant_chain_restaurant_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
