# Generated by Django 4.0.4 on 2022-05-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurant_menu_menuitem_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='decription',
            new_name='description',
        ),
    ]
